# Generated by Django 4.2.13 on 2026-05-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='courses.course')),
            ],
            options={
                'verbose_name': 'Séquence pédagogique',
                'verbose_name_plural': 'Séquences pédagogiques',
                'ordering': ['cours', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ressource', models.CharField(choices=[('texte', 'Contenu textuel'), ('video', 'Vidéo pédagogique'), ('document', 'Document pédagogique'), ('quiz', 'Quiz'), ('activite', 'Activité interactive'), ('evaluation', 'Évaluation')], max_length=20, verbose_name='Type de ressource')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('complexite', models.CharField(choices=[('simple', 'Simple'), ('moyenne', 'Moyenne'), ('complexe', 'Complexe')], default='moyenne', max_length=20, verbose_name='Complexité')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='teachers.teacher')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.sequence')),
            ],
            options={
                'verbose_name': 'Ressource pédagogique',
                'verbose_name_plural': 'Ressources pédagogiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
