# Generated by Django 4.2.13 on 2026-05-24 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_report', models.CharField(choices=[('individuel', 'Fiche individuelle'), ('global', 'État global'), ('paiement', 'État de paiement'), ('statistique', 'Statistiques pédagogiques')], max_length=20)),
                ('annee_academique', models.CharField(max_length=9, verbose_name='Année académique')),
                ('total_heures', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teachers.teacher', verbose_name='Enseignant')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_generation'],
            },
        ),
    ]
