# Generated by Django 4.2.13 on 2026-05-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '__first__'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=9, unique=True, verbose_name='Libellé (ex: 2025-2026)')),
                ('en_cours', models.BooleanField(default=False, verbose_name='Année en cours')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('creation', 'Création de ressource'), ('mise_a_jour', 'Mise à jour de ressource')], max_length=20, verbose_name="Type d'activité")),
                ('heures', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures attribuées')),
                ('annee_academique', models.CharField(help_text='Format : 2025-2026', max_length=9, verbose_name='Année académique')),
                ('date_activite', models.DateField(verbose_name="Date de l'activité")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teachers.teacher')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Activité pédagogique',
                'verbose_name_plural': 'Activités pédagogiques',
                'ordering': ['-date_activite'],
            },
        ),
    ]
